
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND BOOLEAN LPAREN NOT OR RPARENexpression : expression AND term\n                  | expression OR termexpression : termterm : NOT factorterm : factorfactor : LPAREN expression RPARENfactor : BOOLEAN'
    
_lr_action_items = {'NOT':([0,5,7,8,],[3,3,3,3,]),'LPAREN':([0,3,5,7,8,],[5,5,5,5,5,]),'BOOLEAN':([0,3,5,7,8,],[6,6,6,6,6,]),'$end':([1,2,4,6,9,11,12,13,],[0,-3,-5,-7,-4,-1,-2,-6,]),'AND':([1,2,4,6,9,10,11,12,13,],[7,-3,-5,-7,-4,7,-1,-2,-6,]),'OR':([1,2,4,6,9,10,11,12,13,],[8,-3,-5,-7,-4,8,-1,-2,-6,]),'RPAREN':([2,4,6,9,10,11,12,13,],[-3,-5,-7,-4,13,-1,-2,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,5,],[1,10,]),'term':([0,5,7,8,],[2,2,11,12,]),'factor':([0,3,5,7,8,],[4,9,4,4,4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression AND term','expression',3,'p_expression_binop','logico_validar_p.py',10),
  ('expression -> expression OR term','expression',3,'p_expression_binop','logico_validar_p.py',11),
  ('expression -> term','expression',1,'p_expression_term','logico_validar_p.py',15),
  ('term -> NOT factor','term',2,'p_term_not','logico_validar_p.py',19),
  ('term -> factor','term',1,'p_term_factor','logico_validar_p.py',23),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_group','logico_validar_p.py',27),
  ('factor -> BOOLEAN','factor',1,'p_factor_boolean','logico_validar_p.py',31),
]
